### ISSUE TITLE
Doctrine Message Repository is using dbal 3.1+

### ISSUE THREAD

**Issue by Nek-** [EventSaucePHP/MessageStorageMonoRepo#2]
This is an issue because barely anything is currently compatible with dbal 3.1+ in the ecosystem. Not even doctrine/migrations.

You should consider changing minimum version requirements.

**Comment by frankdejonge** [comment]
Would 3.0 be ok?

**Comment by Nek-** [comment]
No, actually it would be a super great idea to support dbal 2.x.

**Comment by frankdejonge** [comment]
It now contains a version for doctrine dbal ^2.6
